apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flycatch-website
  labels:
    app.kubernetes.io/name: flycatch-website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  # Do not add Traefik noindex middleware on production.
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.flycatchtech.com
      secretName: flycatch-website-prod-tls
  rules:
    - host: www.flycatchtech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
