apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http01
  labels:
    app.kubernetes.io/name: flycatch-website
spec:
  acme:
    email: liju@flycatchtech.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http01-account
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
