app:
  name: flycatch-website

registry: registry.k3s.flycatchtech.in

build:
  techStack: node
  dockerfile: apps/Frontend/Dockerfile
  context: apps/Frontend
  args: {}

sonar:
  enabled: true
  host: https://sonarqube.flycatchtech.in/
  projectKey: flycatch-website

notifications:
  enabled: true

deploy:
  enabled: false
  strategy: recreate
  script: deploy.sh
  paths: {}

branches:
  "feat/harbor-test":
    environment: dev
    imageTag: harbor-test
    build: true
    sonar: true
    docker: true
    deploy: false

ci:
  pullRequests:
    build: true
    sonar: false
    docker: false
    deploy: false