"""Populate query fragments for Strapi collections."""

from __future__ import annotations

from typing import Any

# Prefer deep-enough populate; Strapi v4 `*` covers one level; nested media uses explicit maps.
POPULATE: dict[str, str | dict[str, Any]] = {
    "categories": "*",
    "contenttype-categories": "*",
    "industries": "*",
    "technologies": "*",
    "news-categories": "*",
    "resource-categories": "*",
    "blogs": {
        "image": True,
        "thumbnail_image": True,
        "writer_image": True,
        "author": True,
        "categories": True,
        "seo": True,
    },
    "case-studies": {
        "image": True,
        "industry": True,
        "technologies": {"populate": {"logo": True}},
        "contenttype_categories": True,
        "seo": True,
    },
    "news": {
        "image": True,
        "author": True,
        "news_categories": True,
        "categories": True,
        "seo": True,
    },
    "resources": {
        "image": True,
        "pdf_document": True,
        "categories": True,
        "seo": True,
    },
    "client-logos": {
        "colour_logo": True,
        "white_logo": True,
        "color_logo": True,
    },
    "client-testimonials": {"image": True},
    "employee-testimonials": {"image": True},
    "openings": "*",
    "applications": {"resume": True, "opening": True, "openings": True},
    "downloads": {"file": True, "pdf": True, "document": True},
    "awards": {"images": {"populate": {"image": True}}, "seo": True},
    "contacts": "*",
    "subscriptions": "*",
    "homepages": {
        "seo": True,
        "video_file": True,
        "banner_video": True,
        "services_section": {"populate": {"services_image": True}},
        "case_studies": True,
        "faqs": True,
    },
    "homepage-seo": "*",
    "solutions": {"seo": True, "banner_image": True},
    "solution-details": {
        "banner": {"populate": {"image": True}},
        "introduction": {"populate": {"image": True, "icons": True, "title": True}},
        "challenges": {
            "populate": {"image": True, "title": True, "types": {"populate": {"image": True}}}
        },
        "benefits": {"populate": {"title": True, "types": {"populate": {"image": True}}}},
        "solutions_section": True,
        "cta": {"populate": {"title": True}},
        "seo": True,
    },
    "products": {
        "product_logo": True,
        "product_card_image": True,
        "product_banner_image": True,
        "seo": True,
    },
    "ai-services": {
        "banner_image": True,
        "ai_expertise_image": True,
        "seo": True,
        "industry_section": {"populate": {"industry_images": True}},
        "solutions_sections": True,
        "ai_expertise_accordian": True,
        "faq_accordion": True,
        "faq_accordian": True,
        "faqs": True,
    },
    "cloud-services": {
        "seo": True,
        "banner_image": True,
        "cloud_service_offering_image": True,
        "cloud_service_accordion": True,
        "faq_accordion": True,
    },
    "data-and-analytics": {
        "seo": True,
        "banner_image": True,
        "offering_image": True,
        "accordion_section": True,
        "faq_accordion": True,
    },
    "digital-transformations": {
        "seo": True,
        "banner_image": True,
        "outcomes_image": True,
        "digital_transformation_accordion": True,
        "faq_accordion": True,
    },
    "application-development-services": {
        "seo": True,
        "banner_image": True,
        "offering_img": True,
        "application_development_accordion": True,
        "faq_accordion": True,
    },
    "application-modernizations": {
        "seo": True,
        "banner_image": True,
        "application_modernization_offering_image": True,
        "application_modernization_accordion": True,
        "faq_accordion": True,
    },
    "mobile-application-developments": {
        "seo": True,
        "banner_image": True,
        "offering_image": True,
        "mobile_application_accordion": True,
        "faq_accordion": True,
    },
    "user-centered-designs": {
        "seo": True,
        "banner_image": True,
        "offering_image": True,
        "accordion_section": True,
        "faq_accordion": True,
    },
    "dev-ops-consultations": {
        "seo": True,
        "banner_image": True,
        "experience_image": True,
        "experience_accordion": True,
        "faq_accordion": True,
    },
    "infrastructure-management-and-automations": {
        "seo": True,
        "banner_image": True,
        "faq_accordion": True,
    },
    "services": {"seo": True, "banner_image": True},
    "flycatch-saudi-arabias": {
        "seo": True,
        "flycatch_saudi_arabia_banner_image": True,
        "video_file": True,
        "services_section": {"populate": {"services_image": True}},
    },
}

# Live controllers that return a bare JSON array instead of {data, meta}.
BARE_ARRAY_COLLECTIONS: frozenset[str] = frozenset(
    {
        "client-testimonials",
        "employee-testimonials",
        "downloads",
        "homepages",
        "homepage-seo",
    }
)

# Logical import step names → Strapi collection path(s)
STEP_COLLECTIONS: dict[str, list[str]] = {
    "categories": ["categories"],
    "case-study-categories": ["contenttype-categories"],
    "industries": ["industries"],
    "technologies": ["technologies"],
    "news-categories": ["news-categories"],
    "resource-categories": ["resource-categories"],
    "authors": ["blogs"],  # derived from blogs
    "blogs": ["blogs"],
    "case-studies": ["case-studies"],
    "news": ["news"],
    "resources": ["resources"],
    "client-logos": ["client-logos"],
    "client-testimonials": ["client-testimonials"],
    "employee-testimonials": ["employee-testimonials"],
    "openings": ["openings"],
    "applications": ["applications"],
    "downloads": ["downloads"],
    "memberships": ["awards"],
    "contacts": ["contacts"],
    "homes": ["homepages", "homepage-seo"],
    "solutions": ["solutions"],
    "solution-details": ["solution-details"],
    "solution-products": ["products"],
    "ai-services": ["ai-services"],
    "cloud-services": ["cloud-services"],
    "data-analytics": ["data-and-analytics"],
    "digital-transformation": ["digital-transformations"],
    "application-development": ["application-development-services"],
    "application-modernization": ["application-modernizations"],
    "mobile-application-development": ["mobile-application-developments"],
    "user-centered-design": ["user-centered-designs"],
    "devops-consult": ["dev-ops-consultations"],
    "infrastructure-management": ["infrastructure-management-and-automations"],
    "overview": ["services"],
    "flycatch-saudi-arabia": ["flycatch-saudi-arabias"],
}

IMPORT_ORDER: list[str] = [
    "categories",
    "case-study-categories",
    "industries",
    "technologies",
    "news-categories",
    "resource-categories",
    "authors",
    "blogs",
    "case-studies",
    "news",
    "resources",
    "client-logos",
    "client-testimonials",
    "employee-testimonials",
    "openings",
    "applications",
    "downloads",
    "memberships",
    "contacts",
    "solution-details",
    "solution-products",
    "solutions",
    "homes",
    "ai-services",
    "cloud-services",
    "data-analytics",
    "digital-transformation",
    "application-development",
    "application-modernization",
    "mobile-application-development",
    "user-centered-design",
    "devops-consult",
    "infrastructure-management",
    "overview",
    "flycatch-saudi-arabia",
]
