apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flycatch-website-dev

resources:
- ../../base
- ingress.yaml
- noindex-middleware.yaml

images:
- name: registry.k3s.flycatchtech.in/flycatch-website/administration-fe
  newName: registry.k3s.flycatchtech.in/flycatch-website/administration-fe
  newTag: c01d72bbecace3a026051d542625da843421c1e9
- name: registry.k3s.flycatchtech.in/flycatch-website/backend
  newName: registry.k3s.flycatchtech.in/flycatch-website/backend
  newTag: c01d72bbecace3a026051d542625da843421c1e9
- name: registry.k3s.flycatchtech.in/flycatch-website/frontend
  newName: registry.k3s.flycatchtech.in/flycatch-website/frontend
  newTag: c01d72bbecace3a026051d542625da843421c1e9

replicas:
- count: 1
  name: backend
- count: 1
  name: frontend
- count: 1
  name: administration-fe
- count: 1
  name: gateway
