apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flycatch-website-dev

resources:
- ../../base
- ingress.yaml
- noindex-middleware.yaml

images:
- name: registry.k3s.flycatchtech.in/flycatch-website/administration-fe
  newName: registry.k3s.flycatchtech.in/flycatch-website/administration-fe
  newTag: 2dac8187bebf44a11bef07dd3b99ed7aec6c3acb
- name: registry.k3s.flycatchtech.in/flycatch-website/backend
  newName: registry.k3s.flycatchtech.in/flycatch-website/backend
  newTag: 2dac8187bebf44a11bef07dd3b99ed7aec6c3acb
- name: registry.k3s.flycatchtech.in/flycatch-website/frontend
  newName: registry.k3s.flycatchtech.in/flycatch-website/frontend
  newTag: 2dac8187bebf44a11bef07dd3b99ed7aec6c3acb

replicas:
- count: 1
  name: backend
- count: 1
  name: frontend
- count: 1
  name: administration-fe
- count: 1
  name: gateway
